# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/kavya/Desktop/forked/verilog-ethernet/example/AX7203_ARTIX7/fpga/fpga/fpga.srcs/sources_1/ip/clk_div/clk_div.xci
# IP: The module: 'clk_div' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/kavya/Desktop/forked/verilog-ethernet/example/AX7203_ARTIX7/fpga/fpga/fpga.gen/sources_1/ip/clk_div/clk_div_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_div'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/kavya/Desktop/forked/verilog-ethernet/example/AX7203_ARTIX7/fpga/fpga/fpga.gen/sources_1/ip/clk_div/clk_div.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_div'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/kavya/Desktop/forked/verilog-ethernet/example/AX7203_ARTIX7/fpga/fpga/fpga.gen/sources_1/ip/clk_div/clk_div_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_div'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/kavya/Desktop/forked/verilog-ethernet/example/AX7203_ARTIX7/fpga/fpga/fpga.srcs/sources_1/ip/clk_div/clk_div.xci
# IP: The module: 'clk_div' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/kavya/Desktop/forked/verilog-ethernet/example/AX7203_ARTIX7/fpga/fpga/fpga.gen/sources_1/ip/clk_div/clk_div_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_div'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/kavya/Desktop/forked/verilog-ethernet/example/AX7203_ARTIX7/fpga/fpga/fpga.gen/sources_1/ip/clk_div/clk_div.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_div'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/kavya/Desktop/forked/verilog-ethernet/example/AX7203_ARTIX7/fpga/fpga/fpga.gen/sources_1/ip/clk_div/clk_div_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_div'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
